sample_dotnet_mvc/Models/ErrorViewModel.cs
using System;

namespace sample_dotnet_mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

sample_dotnet_mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using sample_dotnet_mvc.Models;

namespace sample_dotnet_mvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Message()
        {
            ViewData["Title"]="Sai Message";
            ViewData["Message"] = "Site Under Development";
            return View();
        }

        public IActionResult Photo()
        {
            ViewData["Title"] = "Photo Gallery";
            ViewData["Message"] = "Site Under Development";
            return View();
        }

        public IActionResult Donation()
        {
            ViewData["Title"] = "Donation Account Information";
            return View();
        }

        public IActionResult About()
        {
            ViewData["Title"] = "About Us";
            ViewData["Message"] = "Your application description page.";

            return View();
        }


        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

sample_dotnet_mvc/Controllers/SideController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using sample_dotnet_mvc.Models;

namespace sample_dotnet_mvc.Controllers
{
    public class SideController : Controller
    {

		public IActionResult Saiblog()
		{
			ViewData["Title"] = "SaiBlog";
			ViewData["Message"] = "Site Under Development";
			return View();
		}


		public IActionResult Information()
		{
			ViewData["Title"] = "Information";
			ViewData["Message"] = "Site Under Development";
			return View();
		}

        public IActionResult Current()
        {
            ViewData["Title"] = "Current Project";
            ViewData["Message"] = "Site Under Development";
            return View();
        }

		public IActionResult FuturePlan()
		{
			ViewData["Title"] = "Future Plan Project";
			ViewData["Message"] = "Site Under Development";
			return View();
		}

		public IActionResult Suggestion()
		{
			ViewData["Title"] = "Suggestion";
			ViewData["Message"] = "Site Under Development";
			return View();
		}

		public IActionResult News()
		{
			ViewData["Title"] = "Future Plan Project";
			ViewData["Message"] = "Site Under Development";
			return View();
		}
        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page is from Side Controller.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

sample_dotnet_mvc/Views/Home/About.cshtml
@{
  //ViewData["Title"] = "About";
  Layout="_Layout";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

sample_dotnet_mvc/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

sample_dotnet_mvc/Views/Home/Donation.cshtml
@{
  //ViewData["Title"] = "About";
  Layout="_Layout";
}
<div class='container'>
  <div class='row centered-form'>
    <div class='col-xs-10 col-sm-10'>
      <div class='panel panel-default'>
        <div class='panel-heading'>
            <h2 class='panel-title'><strong>@ViewData["Title"]</strong></h2>
        </div>
        <div class='panel-body'>
          <form role='form'>
            <div class='row'>
              <div class='col-xs-6 col-sm-6 col-md-6'>
                <div class="form-group">
                  <label>Account Name: </label>
                  <label id='account_name' class='text-primary'>SHREE SAI BABA SAMAGIK KALYAN TRUST</label>
                </div>
              </div>
            </div>
            <div class='row'>
              <div class='col-xs-4 col-sm-4 col-md-4'>
                <div class='form-group'>
                  <label>Account Number: </label>
                  <label id='account_number' class='text-primary'>37054769402</label>
                </div>
              </div>
              <div class='col-xs-4 col-sm-4 col-md-4'>
                <div class='form-group'>
                  <label>IFSC CODE: </label>
                  <label id='code' class='text-primary'>SBIN0016777</label>
                </div>
              </div>
              <div class='col-xs-4 col-sm-4 col-md-4'>
                <div class='form-group'>
                  <label>Branch: </label>
                  <label id='branch' class='text-primary'>DEORIA,MUZAFFARPUR</label>
                </div>
              </div>
            </div>
            <div class='row'>
              <div class='col-xs-6 col-sm-6 col-md-6'>
                <div class='form-group'>
                  <label>Bank: </label>
                  <label id='bank_name' class='text-primary'>STATE BANK OF INDIA</label>
                </div>
              </div>
            </div>
            <div class='row'>
              <div class='col-xs-6 col-sm-6 col-md-6'>
                <div class='form-group'>
                    <label>Address</label>
                    <address>
                      <strong id='bank_address' class='text-primary'>SHREE SAI BABA SAMAGIK KALYAN TRUST</strong><br>
                        Sohasa , Deoria<br>
                        Muzaffarpur, India 843120<br>
                    </address>
                </div>
              </div>
            </div>   
              <div id='contacts' class='row'>
                <div class='col-xs-6 col-sm-6 col-md-6'>
                  <div  class='form-group'>
                    <label>Contact Person 1:</label>
                    <address>
                      <strong class='text-primary'>RAJIV RANJAN</strong><br>
                        Ph#: 9470000157<br>
                      </address>
                  </div>
                </div>
                <div class='col-xs-6 col-sm-6 col-md-6'>
                  <div class='form-group'>
                    <label>Conact Person 2:</label>
                    <address>
                      <strong class='text-primary'>SHRIKANTH PANDEY</strong><br>
                        Ph#: 9939449774<br>
                    </address>
                  </div>
                </div>
              </div>
             </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

sample_dotnet_mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/Saibaba1.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>Shirdi Sai Baba Photo</p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/Saibaba2.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>Sai Temple construction Site</p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/Saibaba3.jpg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>Art of Sharing</p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/Saibaba4.jpg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>Sai Temple construction Plan</p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<!--<div class="row">-->
<span>
        <h2 class='sai-mission'>Trust Mission</h2>
        <ul id='trust-visions'>
			<li class="vision-list">
                     <a href='#' class='visions'>
                        Shree Sai Baba Samagik Kalyan Trust Education Center</a>
                        <p class='vision-para'>Vision to provide free and quality education to destitute family</p>        
            </li>
			<li class="vision-list">
                     <a href='#' class='visions'>
                        Shree Sai Baba Samagik Kalyan Trust Health Care</a>
                        <p class='vision-para'>Vision to provide free and quality health care to everyone in need</p>        
            </li>
			<li class="vision-list" >
                     <a href='#' class='visions'>
                        Shree Sai Baba Samagik Kalyan Trust Water Plant</a>
                        <p class='vision-para'>Vision to provide free clean drinking water to everyone</p>        
            </li>
			<li class="vision-list">
                     <a href='#' class='visions'>
                        Shree Sai Baba Samagik Kalyan Trust Retirement Home</a>
                        <p class='vision-para'>Vision to provide food and shelter for senior citizens</p>        
            </li>
			<li class="vision-list">
               <a href='#' class='visions'>
                        Other Services</a>
                        <p class='vision-para'>Meal Service, Sai Puja Gathering, Recreation Activities</p>        
            </li>
        </ul>
</span>
<!--</div>-->

sample_dotnet_mvc/Views/Home/Message.cshtml
@{
  //ViewData["Title"] = "About";
  Layout="_Layout";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

sample_dotnet_mvc/Views/Home/Photo.cshtml
@{
  //ViewData["Title"] = "About";
  Layout="_Layout";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

sample_dotnet_mvc/Views/Shared/HeaderNavigation.cshtml
<div class="menu-option">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="pills" >HOME</a>
        <a asp-area="" asp-controller="Home" asp-action="Message" class="pills" >MESSAGE</a>
        <a asp-area="" asp-controller="Home" asp-action="Photo" class="pills" >PHOTOS</a>
        <a asp-area="" asp-controller="Home" asp-action="Donation" class="pills">DONATION</a>
		<a asp-area="" asp-controller="Home" asp-action="About" class="pills" >ABOUT US</a>
</div>

sample_dotnet_mvc/Views/Shared/Pageheader.cshtml
<!--The content below is only a placeholder and can be replaced.-->
<div class='page-header header-div'>
	<img src="~/images/top-left.jpg" alt='Sai Baba Image' class="img-responsive" id='image-size' />
    <div class='header-d'>
        <h1 class='header-h'>Shree Sai Baba Samagik Kalyan Trust</h1>
        <p class='address'>Sohansha , Deoria, Dist- Muzaffarpur, Bihar, India, Pincode 843120</p>
    </div>
	 <img src="~/images/top-right-image.jpg" alt='Sai Baba Image' class="img-responsive" id='image-size' />
</div>
@Html.Partial("HeaderNavigation")

sample_dotnet_mvc/Views/Shared/SideNav.cshtml
<div id='veritical-menu-bar' class='side-menu-bar '>
    <span >
        <a asp-area="" asp-controller="Side" asp-action="Saiblog" class='btn paper-flatten'>Sai Blog</a>
        <a asp-area="" asp-controller="Side" asp-action="Information" class='btn paper-flatten'>Information</a>
        <a asp-area="" asp-controller="Side" asp-action="Current" class='btn paper-flatten'>On Going Project</a>
        <a asp-area="" asp-controller="Side" asp-action="FuturePlan" class='btn paper-flatten'>Future Plan</a>
        <a asp-area="" asp-controller="Side" asp-action="Suggestion" class='btn paper-flatten'>Suggestion</a>
		<a asp-area="" asp-controller="Side" asp-action="News" class='btn paper-flatten'>News</a>
        <a asp-area="" asp-controller="Side" asp-action="Contact" class='btn paper-flatten'>Contact Us</a>
    </span>
</div>                             
                                    

sample_dotnet_mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shree Sai Baba Samagik Kalyan Trust</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
		<link rel="stylesheet" href="~/css/pageheader.css" />
        <link rel="stylesheet" href="~/css/HeaderNav.css" />
		<link rel="stylesheet" href="~/css/sideNav.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
		<link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/pageheader.css" />
        <link rel="stylesheet" href="~/css/HeaderNav.css" />
        <link rel="stylesheet" href="~/css/sideNav.css" />
    </environment>
</head>
<body>
		@Html.Partial("PageHeader")
    <div class="content-align">  
		@Html.Partial("SideNav")
       <div class="container body-content">
		@RenderBody()
       </div>

    </div>
	<footer id="nav-footer" class="nav-footer">
            <div class="footer-group">
                    <ul class="footer-list">
                        <li><a asp-area="" asp-controller="Home" asp-action="About">ABOUT US |</a></li>
                        <li><a asp-area="" asp-controller="Side" asp-action="Contact">CONTACT US </a></li>
                        <li class="footer-social">
                            <a href="https://www.facebook.com" class="only-icon">
                                <i aria-hidden="true" class="icon-facebook"></i>
                                <span>facebook</span>
                            </a>
                        </li>
                    </ul>

            </div>
            <div class="contentinfo">
            <p>&copy; 2017 - Shri Sai Baba Kalyan Trust</p>
            <p>Content is available Under these
                        <a href="/"> licenses</a></p>
            </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

sample_dotnet_mvc/Views/Side/Contact.cshtml
@{
  //ViewData["Title"] = "About";
  Layout="_Layout";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

sample_dotnet_mvc/Views/Side/Current.cshtml
@{
  //ViewData["Title"] = "About";
  Layout="_Layout";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

sample_dotnet_mvc/Views/Side/FuturePlan.cshtml
@{
  //ViewData["Title"] = "About";
  Layout="_Layout";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

sample_dotnet_mvc/Views/Side/Information.cshtml
@{
  //ViewData["Title"] = "About";
  Layout="_Layout";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

sample_dotnet_mvc/Views/Side/News.cshtml
@{
  //ViewData["Title"] = "About";
  Layout="_Layout";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

sample_dotnet_mvc/Views/Side/Saiblog.cshtml
@{
  //ViewData["Title"] = "About";
  Layout="_Layout";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

sample_dotnet_mvc/Views/Side/Suggestion.cshtml
@{
  //ViewData["Title"] = "About";
  Layout="_Layout";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>